@startuml
title MOR.7: Przeglądaj wszystkie swoje rezerwacje

autoactivate on
participant ReservationEndpoint
participant "ReservationManager\nTransactionAttribute.REQUIRES_NEW" as ReservationManager
control "ReservationFacadeReadCommitted\nTransactionAttribute.MANDATORY" as ReservationFacade
autonumber

ReservationEndpoint -> ReservationManager: getAllCustomersReservations(login, getCanceled, getPast)
        ReservationManager -> ReservationFacade: findByCustomer(login, getCanceled, getPast)
        return list of customer's reservations
return list of customer's reservations

@enduml