@startuml
title
MOR.8 Przeglądaj szczegóły rezerwacji
end title

autoactivate on
participant ReservationEndpoint
participant "ReservationManager\nTransactionAttribute.REQUIRES_NEW" as ReservationManager
control "ReservationFacadeReadCommitted\nTransactionAttribute.MANDATORY" as ReservationFacadeReadCommitted
alt reservation exists
autonumber

            ReservationEndpoint -> ReservationManager: getReservation(reservationNumber)

                    ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                    return optional with reservation

            return reservation
else reservation does not exists
autonumber
 
                 ReservationEndpoint -> ReservationManager: getReservation(reservationNumber)

                         ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                         return empty optional

                 return reservation does not exist

end
@enduml
