@startuml
title
MOR.9 Przeglądaj szczegóły swojej rezerwacji
end title

autoactivate on
participant ReservationEndpoint
participant SecurityContext
participant "ReservationManager\nTransactionAttribute.REQUIRES_NEW" as ReservationManager
control "ReservationFacadeReadCommitted\nTransactionAttribute.MANDATORY" as ReservationFacadeReadCommitted
entity ReservationEntity
entity CustomerEntity
entity AccountEntity
alt reservation exists and belongs to user
autonumber

            ReservationEndpoint -> ReservationManager: getOwnReservation(login, reservationNumber)
                
                    ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                    return optional with reservation
                    ReservationManager -> ReservationEntity: getCustomer()
                    return optional with Customer
                    ReservationManager -> CustomerEntity: getAccount()
                    return account
                    ReservationManager -> AccountEntity: getLogin()
                    return account login
            
            return reservation

else reservation does not belong to user
autonumber

                 ReservationEndpoint -> ReservationManager: getOwnReservation(login, reservationNumber)
                     
                    ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                    return optional with reservation
                    ReservationManager -> ReservationEntity: getCustomer()
                    return optional with Customer
                    ReservationManager -> CustomerEntity: getAccount()
                    return account
                    ReservationManager -> AccountEntity: getLogin()
                    return account login

                 return reservation does not belong to user

else reservation does not exists
autonumber

                 ReservationEndpoint -> ReservationManager: getOwnReservation(login, reservationNumber)
                     
                         ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                         return empty optional

                 return reservation does not exist

end
@enduml
