@startuml
title MOR.18 Przeglądaj szczegóły toru
autoactivate on
participant AlleyEndpoint
participant "AlleyManager\nTransactionAttribute.REQUIRES_NEW" as AlleyManager
participant "AlleyDifficultyLevelManager\nTransactionAttribute.REQUIRES_NEW" as  AlleyDifficultyLevelManager
control "AlleyFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AlleyFacade
control "AlleyDifficultyLevelFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AlleyDifficultyLevelFacade

alt alley details displayed properly
autonumber
                    AlleyEndpoint -> AlleyManager: getAlleyDetails(name)
                        AlleyManager -> AlleyFacade: findByName(name)
                        return optional with alley
                        AlleyManager -> AlleyEntity: isActive()
                        return true
                    return alley

                    note right AlleyEndpoint
                        [...]
                    end note

                    AlleyEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()
                        AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacade: findAll()
                        return alleyDifficultyLevelsEntityList
                    return alleyDifficultyLevelsEntityList
else alley does not exist
autonumber
                    AlleyEndpoint -> AlleyManager: getAlleyDetails(name)
                        AlleyManager -> AlleyFacade: findByName(name)
                        return empty optional
                    return failed
else alley was removed
autonumber
                    AlleyEndpoint -> AlleyManager: getAlleyDetails(name)
                        AlleyManager -> AlleyFacade: findByName(name)
                        return optional with alley
                        AlleyManager -> AlleyEntity: isActive()
                        return false
                    return failed
else no alley difficulty levels
autonumber
                    AlleyEndpoint -> AlleyManager: getAlleyDetails(name)
                        AlleyManager -> AlleyFacade: findByName(name)
                        return optional with alley
                    return alley

                    note right AlleyEndpoint
                        [...]
                    end note

                    AlleyEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()
                            AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacade: findAll()
                            return empty list
                    return failed
end
@enduml