@startuml
title
MOR.14 Dodaj nowy tor
end title

autoactivate on
participant AlleyEndpoint
participant AlleyDifficultyLevelEndpoint
participant "AlleyManager\nTransactionAttribute.REQUIRES_NEW" as AlleyManager
participant "AlleyDifficultyLevelManager\nTransactionAttribute.REQUIRES_NEW" as AlleyDifficultyLevelManager
control "AlleyFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AlleyFacadeReadCommitted
control "AlleyDifficultyLevelFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AlleyDifficultyLevelFacadeReadCommitted
alt correct
autonumber

            AlleyDifficultyLevelEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()

                AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacadeReadCommitted: findAll()
                return list of all alley difficulty levels

            return list of all alley difficulty levels
    note right of AlleyEndpoint
    [...]
    end note

            AlleyEndpoint -> AlleyManager: addAlley(alley, alleyDifficultyLevelName)

                    AlleyManager -> AlleyDifficultyLevelFacadeReadCommitted: findByName(alleyDifficultyLevelName)
                    return optional with alleyDifficultyLevelEntity
                    AlleyManager -> AlleyEntity: setDifficultyLevel(alleyDifficultyLevelEntity)
                    return
                    AlleyManager -> AlleyEntity: getName()
                    return alleyName
                    AlleyManager -> AlleyFacadeReadCommitted: findByName(alleyName)
                    return empty optional
                    AlleyManager -> AlleyFacadeReadCommitted: create(alley)
                    return success

            return success

else no alley difficulty levels
 autonumber

             AlleyDifficultyLevelEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()

                 AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacadeReadCommitted: findAll()
                 return list of all alley difficulty levels

             return no alley difficulty levels

else invalid form
 autonumber

             AlleyDifficultyLevelEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()

                 AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacadeReadCommitted: findAll()
                 return list of all alley difficulty levels

             return list of all alley difficulty levels




else alley difficulty level does not exist
autonumber

            AlleyDifficultyLevelEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()

                AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacadeReadCommitted: findAll()
                return list of all alley difficulty levels

            return list of all alley difficulty levels

    note right of AlleyEndpoint
    [...]
    end note

             AlleyEndpoint -> AlleyManager: addAlley(alley, alleyDifficultyLevelName)

                   AlleyManager -> AlleyDifficultyLevelFacadeReadCommitted: findByName(alleyDifficultyLevelName)
                   return empty optional

             return alley difficulty level does not exist

else alley with such name exists
autonumber

            AlleyDifficultyLevelEndpoint -> AlleyDifficultyLevelManager: getAllAlleyDifficultyLevels()

                AlleyDifficultyLevelManager -> AlleyDifficultyLevelFacadeReadCommitted: findAll()
                return list of all alley difficulty levels

            return list of all alley difficulty levels

    note right of AlleyEndpoint
    [...]
    end note


             AlleyEndpoint -> AlleyManager: addAlley(alley, alleyDifficultyLevelName)

                     AlleyManager -> AlleyDifficultyLevelFacadeReadCommitted: findByName(alleyDifficultyLevelName)
                      return optional with alleyDifficultyLevelEntity
                      AlleyManager -> AlleyEntity: setDifficultyLevel(alleyDifficultyLevelEntity)
                      return
                      AlleyManager -> AlleyEntity: getName()
                      return alleyName
                      AlleyManager -> AlleyFacadeReadCommitted: findByName(alleyName)
                      return optional with alley

             return alley with such name exists



end
@enduml
