@startuml
title
MOR.17 Przeglądaj wszystkie tory
end title

autoactivate on
participant AlleyEndpoint
participant "AlleyManager\nTransactionAttribute.REQUIRES_NEW" as AlleyManager
control "AlleyFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AlleyFacade
autonumber
AlleyEndpoint -> AlleyManager: getAllActiveAlleys()
    AlleyManager -> AlleyFacade: findByActive(true)
    return list of all alleys
return list of all alleys
@enduml
