@startuml

title MOR.24 Dodaj nowy egzemplarz broni
autoactivate on

participant WeaponEndpoint
participant WeaponModelEndpoint
participant "WeaponManager\nTransactionAttribute.REQUIRES_NEW" as WeaponManager
participant "WeaponModeManager\nTransactionAttribute.REQUIRES_NEW" as WeaponModeManager
control "WeaponFacadeSerializable\nTransactionAttribute.MANDATORY" as WeaponFacadeSerializable
control "WeaponModelFacadeReadCommitted\nTransactionAttribute.MANDATORY" as WeaponModelFacade
control "WeaponModelFacadeSerializable\nTransactionAttribute.MANDATORY" as WeaponModelFacadeSerializable

alt provided data is valid
autonumber
    WeaponModelEndpoint -> WeaponModeManager: getAllActiveWeaponModels()
        WeaponModeManager -> WeaponModelFacade : findByActive(true)
        return list of weapon models
    return list of weapon models
    note right of WeaponEndpoint
    [...]
    end note
    WeaponEndpoint -> WeaponManager: createWeapon(weaponEntity, weaponDto.getWeaponModelName())
        WeaponManager -> WeaponFacadeSerializable: findBySerialNumber(weaponEntity.getSerialNumber())
        return empty optional
        WeaponManager -> WeaponModelFacadeSerializable : findByName(weaponModelName)
        return optional with weapon model
        WeaponManager -> WeaponEntity : setWeaponModel(weaponModelEntity)
        return success
        WeaponManager -> WeaponFacadeSerializable: create(weaponEntity)
        return success
    return success
else weapon with such serial number exists
autonumber
    WeaponModelEndpoint -> WeaponModeManager: getAllActiveWeaponModels()
        WeaponModeManager -> WeaponModelFacade : findByActive(true)
        return list of weapon models
    return list of weapon models
    note right of WeaponEndpoint
    [...]
    end note
    WeaponEndpoint -> WeaponManager: createWeapon(weaponEntity, weaponDto.getWeaponModelName())
        WeaponManager -> WeaponFacadeSerializable: findBySerialNumber(weaponEntity.getSerialNumber())
        return optional with weapon
    return weapon exists
else no weapon models
autonumber
    WeaponModelEndpoint -> WeaponModeManager: getAllActiveWeaponModels()
        WeaponModeManager -> WeaponModelFacade : findByActive(true)
        return empty list
    return empty list
else invalid form
autonumber
    WeaponModelEndpoint -> WeaponModeManager: getAllActiveWeaponModels()
        WeaponModeManager -> WeaponModelFacade : findByActive(true)
        return list of weapon models
    return list of weapon models
end

@enduml