@startuml
title
MOR.22 Przeglądaj wszystkie modele broni
end title

autoactivate on
participant WeaponModelEndpoint
participant "WeaponModelManager\nTransactionAttribute.REQUIRES_NEW" as WeaponModelManager
control "WeaponModelFacadeReadCommitted\nTransactionAttribute.MANDATORY" as WeaponModelFacade
autonumber
WeaponModelEndpoint -> WeaponModelManager: getAllActiveWeaponModels()
    WeaponModelManager -> WeaponModelFacade: findByActive(true)
    return list of all WeaponModel
return list of all WeaponModel
@enduml