 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name:  app
   namespace: tua-06
   labels:
     app:  app
 spec:
   selector:
     matchLabels:
       app: app
   replicas: 1
   strategy:
     rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 25%
     type: RollingUpdate
   template:
     metadata:
       labels:
         app:  app
     spec:
       containers:
       - name:  app
         image:  jboss/wildfly:latest
        #  resources:
        #    requests:
        #      cpu: 100m
        #      memory: 100Mi
        #    limits:
        #      cpu: 500m
        #      memory: 200Mi
        #  livenessProbe:
        #    tcpSocket:
        #      port: 80
        #    initialDelaySeconds: 5
        #    timeoutSeconds: 5
        #    successThreshold: 1
        #    failureThreshold: 3
        #    periodSeconds: 10
        #  readinessProbe:
        #    httpGet:
        #      path: /_status/healthz
        #      port: 80
        #    initialDelaySeconds: 5
        #    timeoutSeconds: 2
        #    successThreshold: 1
        #    failureThreshold: 3
        #    periodSeconds: 10
         ports:
         - containerPort:  8080
           name:  https
       restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: tua-06
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

---
    
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: tua-06
spec:
  tls:
  - hosts:
    - tua06.apps.okd.cti.p.lodz.pl
    secretName: tls
  rules:
  - host: tua06.apps.okd.cti.p.lodz.pl
    http:
      paths:
      - path: /ssbd01
        pathType: Prefix
        backend:
          serviceName: app
          servicePort: 8080
---
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: app
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: app
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 10