version: "3.1"
services:
  db:
    build: .
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ssbd01admin
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: ssbd01
      MYSQL_ROOT_PASSWORD: example
