version: "3.1"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: ssbd01
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql:rw
  wildfly:
    build: ./wildfly
  proxy:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "443:443"
    environment:
      - NGINX_PORT=443

