Vagrant.configure("2") do |config|

  config.vm.box = "th7nder/isdp-quick-centos"
  # config.vm.box = "centos/7"
  # config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
