@startuml

title MOK.15 Przeglądaj szczegóły konta innego użytkownika

autoactivate on
participant AccountEndpoint
participant "AccountManager\nTransactionAttribute.REQUIRES_NEW" as AccountManager
control "AccountFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AccountFacade

alt account exists
autonumber
                    AccountEndpoint -> AccountManager: getAccountDetails(login)
                                AccountManager -> AccountFacade: findByLogin(login)
                                return optional with account
                    return account

else account does not exist
autonumber
                 AccountEndpoint -> AccountManager: getAccountDetails(login)
                     AccountManager -> AccountManager: findAccountByLogin(login)
                             AccountManager -> AccountFacade: findByLogin(login)
                             return empty optional
                     return failed
                 return failed
end
@enduml

