@startuml
title MOK.16 Przeglądaj konta wszystkich użytkowników
autoactivate on
participant AccountEndpoint
participant "AccountManager\nTransactionAttribute.REQUIRES_NEW" as AccountManager
control "AccountFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AccountFacadeReadCommitted
autonumber
                AccountEndpoint -> AccountManager: getAllAccounts()
                    AccountManager -> AccountFacadeReadCommitted: getAllSortedById()
                    return list of all account

                return list of all accounts
@enduml