@startuml

autoactivate on
participant AccountEndpoint
participant "AccountManager\nTransactionAttributeType.REQUIRES_NEW" as AccountManager
control "AccountFacadeReadCommitted\nTransactionAttributeType.MANDATORY" as AccountFacade

title MOK.11 Przeglądaj szczegóły swojego konta

alt correct
autonumber
    AccountEndpoint -> AccountManager: getAccountDetails(login)
        AccountManager -> AccountFacade: findByLogin(login)
        return optional with account
    return account
else account does not exist
autonumber
    AccountEndpoint -> AccountManager: getAccountDetails(login)
        AccountManager -> AccountFacade: findByLogin(login)
        return empty optional
    return account does not exist
end
@enduml