@startuml
title MOK.21 Wyślij link weryfikacyjny.
autoactivate on

participant AccountEndpoint
participant "AccountManager\nTransactionAttribute.REQUIRES_NEW" as AccountManager
participant EmailSender
participant EmailCreator
control "AccountFacadeReadCommitted\nTransactionAttribute.MANDATORY" as AccountFacadeReadCommitted
entity AccountEntity

alt account exist and is not verified
autonumber
            AccountEndpoint -> AccountManager: sendVerificationLink(login, language)
                AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                return optional with account
                AccountManager -> AccountEntity: isVerified()
                return false
                AccountManager -> EmailCreator: getVerificationEmail(language, \naccountEntity.getEmail(), \nLocalDateTime.now(), \naccountEntity.login)
                return verificationEmail
                AccountManager -> EmailSender: sendEmail(verificationEmail)
                return success
            return success

else user does not exist
autonumber
            AccountEndpoint -> AccountManager: sendVerificationLink(login, language)
                AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                return Empty optional
            return failed

else account is verified
autonumber
            AccountEndpoint -> AccountManager: sendVerificationLink(login, language)
                AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                return optional with account
                AccountManager -> AccountEntity: isVerified()
                return true
            return failed
end
@enduml