@startuml

title MOK.4 Odłącz poziom dostępu od konta
autoactivate on
actor Administrator
boundary AccessLevelsManagementView
participant AccountEndpoint
participant AccountManager
control AccessLevelFacadeReadCommitted as AccessLevelFacade
control AdminFacadeReadCommitted as AdminFacade
entity AccessLevelEntity

alt access level is granted
autonumber
    Administrator -> AccessLevelsManagementView: 'revoke' button clicked
        AccessLevelsManagementView -> AccountEndpoint: revokeLevel(login, accessLevel))
            AccountEndpoint -> AccountManager: revokeAccessLevel(login, accessLevel))
            group RW, read committed
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin(accessLevel, login)
                return optional with accessLevel
                AccountManager -> AccessLevelEntity: isActive()
                return true
                AccountManager -> AccessLevelFacade: countAccountRoles(login)
                return != 1
                AccountManager -> AdminFacade: countActive(true)
                return != 1
                AccountManager -> AccessLevelEntity: setActive(false);
                return success
                AccountManager -> AccessLevelFacade: edit(accessLevel)
                return success
            end
            return success
        return status code 200
    return 'success' message

else access level is already revoked
autonumber
    Administrator -> AccessLevelsManagementView: 'revoke' button clicked
        AccessLevelsManagementView -> AccountEndpoint: revokeLevel(login, accessLevel))
            AccountEndpoint -> AccountManager: revokeAccessLevel(login, accessLevel))
            group RW, read committed
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin(accessLevel, login)
                return optional with accessLevel
                AccountManager -> AccessLevelEntity: isActive()
                return false
            end
            return access level is already revoked
        return status code 400
    return 'failed' message

else account does not exist
autonumber
    Administrator -> AccessLevelsManagementView: 'revoke' button clicked
        AccessLevelsManagementView -> AccountEndpoint: revokeLevel(login, accessLevel))
            AccountEndpoint -> AccountManager: revokeAccessLevel(login, accessLevel))
            group RW, read committed
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin(accessLevel, login)
                return empty optional
            end
            return account does not exist
        return status code 400
    return 'failed' message

else attempt to revoke last access level
autonumber
    Administrator -> AccessLevelsManagementView: 'revoke' button clicked
        AccessLevelsManagementView -> AccountEndpoint: revokeLevel(login, accessLevel))
            AccountEndpoint -> AccountManager: revokeAccessLevel(login, accessLevel))
            group RW, read committed
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin(accessLevel, login)
                return optional with accessLevel
                AccountManager -> AccessLevelEntity: isActive()
                return true
                AccountManager -> AccessLevelFacade: countAccountRoles(login)
                return 1
            end
            return attempt to revoke last access level
        return status code 400
    return 'failed' message

else attempt to revoke admin from last admin
autonumber
    Administrator -> AccessLevelsManagementView: 'revoke' button clicked
        AccessLevelsManagementView -> AccountEndpoint: revokeLevel(login, accessLevel))
            AccountEndpoint -> AccountManager: revokeAccessLevel(login, accessLevel))
            group RW, read committed
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin(accessLevel, login)
                return optional with accessLevel
                AccountManager -> AccessLevelEntity: isActive()
                return true
                AccountManager -> AccessLevelFacade: countAccountRoles(login)
                return != 1
                AccountManager -> AdminFacade: countActive(true)
                return 1
            end
            return attempt to revoke\nadmin from last admin
        return status code 400
    return 'failed' message

else invalid level
autonumber
    Administrator -> AccessLevelsManagementView: 'revoke' button clicked
        AccessLevelsManagementView -> AccountEndpoint: revokeLevel(login, accessLevel))
            AccountEndpoint -> AccountManager: revokeAccessLevel(login, accessLevel))
            group RW, read committed
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin(accessLevel, login)
                return empty optional
            end
            return attempt to revoke\nadmin from last admin
        return status code 400
    return 'failed' message

end
@enduml