@startuml

title MOK.3b Dołącz poziom dostępu do konta
autoactivate on
actor Administrator
boundary AccessLevelsView
participant AccountEndpoint
participant AccountManager
control AccountFacadeReadCommitted as AccountFacade
control AdminFacadeReadCommitted as AdminFacade
control AccessLevelFacadeReadCommitted as AccessLevelFacade
control SecurityContext
entity AccountEntity
entity AccessLevelEntity

alt access level is not granted
autonumber
    Administrator -> AccessLevelsView: 'grant' button clicked
        AccessLevelsView -> AccountEndpoint: grantAdminAccessLevel(login, cardNumber)
            AccountEndpoint -> AccountManager: grantAccessLevel("ROLE_ADMIN", login, cardNumber)
            group RW, read committed
                AccountManager -> AccountFacade: findByLogin(login)
                return optional with account
                AccountManager -> AdminFacade: findByCardNumber(cardNumber)
                return optional with accountEntity
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin("ROLE_ADMIN", login)
                return optional with accessLevelEntity
                opt accessLevelEntity is present
                    AccountManager -> AccessLevelEntity: isActive()
                    return false
                    AccountManager -> AccessLevelEntity: setActive(true)
                    return success
                    AccountManager -> AccessLevelEntity: setCardNumber(cardNumber)
                    return success
                    AccountManager -> AdminFacade: edit(accessLevelEntity)
                    return success
                else accessLevelEntity is empty
                    AccountManager -> AdminEntity **: <<create>>
                    AccountManager -> AdminEntity: setActive(true)
                    return success
                    AccountManager -> AccountEntity: getAccessLevels().add(adminEntity)
                    return success
                    AccountManager -> AdminFacade: create(adminEntity)
                    return success
                end
            end
            return success
        return status code 200
    return 'success' message

else access level is already granted
autonumber
    Administrator -> AccessLevelsView: 'grant' button clicked
        AccessLevelsView -> AccountEndpoint: grantAdminAccessLevel(login, cardNumber)
            AccountEndpoint -> AccountManager: grantAccessLevel("ROLE_ADMIN", login, cardNumber)
            group RW, read committed
                AccountManager -> AccountFacade: findByLogin(login)
                return optional with account
                AccountManager -> AdminFacade: findByCardNumber(cardNumber)
                return optional with accountEntity
                AccountManager -> AccessLevelFacade: findByAccessLevelAndLogin("ROLE_ADMIN", login)
                return optional with accessLevelEntity
                AccountManager -> AccessLevelEntity: isActive()
                return true
            end
            return access level is already granted
        return status code 400
    return 'failed' message

else account does not exist
autonumber
    Administrator -> AccessLevelsView: 'grant' button clicked
        AccessLevelsView -> AccountEndpoint: grantAdminAccessLevel(login, cardNumber)
            AccountEndpoint -> AccountManager: grantAccessLevel("ROLE_ADMIN", login, cardNumber)
            group RW, read committed
                AccountManager -> AccountFacade: findByLogin(login)
                return empty optional
            end
            return account does not exist
        return status code 400
    return 'failed' message

end
@enduml