@startuml
autoactivate on
title MOK.19 Wyloguj się
actor "Admin~/Employee~/Customer"
boundary MainMenu
participant AuthenticationEndpoint
autonumber
    "Admin~/Employee~/Customer" -> MainMenu:click log out button
        MainMenu -> AuthenticationEndpoint: logOut()
        return status code 200
    return log out confirmation
@enduml