@startuml
title
MOK.10 Zmień adres e-mail swojego konta
end title

autoactivate on
actor "Admin~/Employee~/Customer"
boundary ChangeOwnEmailForm
boundary ConfirmationView
participant AccountEndpoint
participant AccountManager
control AccountFacadeReadCommitted
control ExpiredTokenFacadeReadCommitted
entity AccountEntity
entity ExpiredTokenEntity
participant SecurityContext
participant Crypt
participant EmailSender

alt correct
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail, lang, byAdmin=false)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return optional with account
                    AccountManager -> AccountEntity: getEmail()
                    return current account email
                    AccountManager -> AccountFacadeReadCommitted: findByEmail(newEmail)
                    return empty optional
                    AccountManager -> EmailCreator: getEmailForChangeEmail(lang, newEmail, byAdmin, login, newEmail, LocalDateTime.now().toString())
                    return emailMessage
                    AccountManager -> EmailSender: sendEmail(emailMessage)
                    return success
                end
            return success
        return status code 200
    return 'link sent' message
    "Admin~/Employee~/Customer" -> ConfirmationView: link visited
            ConfirmationView -> AccountEndpoint: changeOwnEmail(toVerify)
                AccountEndpoint -> AccountManager: changeEmail(cipherText)
                    group RW, read commited
                        AccountManager -> ExpiredTokenFacadeReadCommitted: findByToken(cipherText)
                        return empty optional
                        AccountManager -> Crypt: decrypt(cipherText)
                        return decrypted login and email
                        AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                        return optional with account
                        AccountManager -> AccountFacadeReadCommitted: findByEmail(email)
                        return empty optional
                        AccountManager -> AccountEntity: setEmail(newEmail)
                        return success
                        AccountManager -> AccountFacadeReadCommitted: edit(account)
                        return success

                        AccountManager -> ExpiredTokenEntity**:<<create>>

                        AccountManager -> ExpiredTokenFacadeReadCommitted: create(expiredToken);
                        return success
                    end
                return success
            return status code 200
        return 'email changed' message
else email does not meet the requirements
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
        return status code 400
    return 'error' message
else invalid captcha
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return negative validation result
        return status code 400
    return 'error' message
else account does not exist
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return empty optional
                end
            return account does not exist
         return status code 400
     return 'error' message
else new email equals old
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return optional with account
                    AccountManager -> AccountEntity: getEmail()
                    return current account email
                end
            return new email equals old
         return status code 400
     return 'error' message
else email already in use
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
            ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
                AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
                return positive validation result
                AccountEndpoint -> SecurityContext: getCallerPrincipal()
                return principal
                AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail)
                    group RO, read committed
                        AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                        return optional with account
                        AccountManager -> AccountEntity: getEmail()
                        return current account email
                        AccountManager -> AccountFacadeReadCommitted: findByEmail(newEmail)
                        return optional with account
                    end
                return email already in use
             return status code 400
     return 'error' message
else link expired
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail, lang, byAdmin=false)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return optional with account
                    AccountManager -> AccountEntity: getEmail()
                    return current account email
                    AccountManager -> AccountFacadeReadCommitted: findByEmail(newEmail)
                    return empty optional
                    AccountManager -> EmailCreator: getEmailForChangeEmail(lang, newEmail, byAdmin, login, newEmail, LocalDateTime.now().toString())
                    return emailMessage
                    AccountManager -> EmailSender: sendEmail(emailMessage)
                    return success
                end
            return success
        return status code 200
    return 'link sent' message
    "Admin~/Employee~/Customer" -> ConfirmationView: link visited
            ConfirmationView -> AccountEndpoint: changeOwnEmail(toVerify)
                AccountEndpoint -> AccountManager: changeEmail(cipherText)
                    group RW, read commited
                        AccountManager -> ExpiredTokenFacadeReadCommitted: findByToken(cipherText)
                        return optional with token
                    end
                return link expired
            return status code 400
        return 'error' message
else link is corrupted
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail, lang, byAdmin=false)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return optional with account
                    AccountManager -> AccountEntity: getEmail()
                    return current account email
                    AccountManager -> AccountFacadeReadCommitted: findByEmail(newEmail)
                    return empty optional
                    AccountManager -> EmailCreator: getEmailForChangeEmail(lang, newEmail, byAdmin, login, newEmail, LocalDateTime.now().toString())
                    return emailMessage
                    AccountManager -> EmailSender: sendEmail(emailMessage)
                    return success
                end
            return success
        return status code 200
    return 'link sent' message
    "Admin~/Employee~/Customer" -> ConfirmationView: link visited
            ConfirmationView -> AccountEndpoint: changeOwnEmail(toVerify)
                AccountEndpoint -> AccountManager: changeEmail(cipherText)
                    group RW, read commited
                        AccountManager -> ExpiredTokenFacadeReadCommitted: findByToken(cipherText)
                        return empty optional
                        AccountManager -> Crypt: decrypt(cipherText)
                        return error
                    end
                return link corrupted
            return status code 400
        return 'error' message
else account deleted before visiting link
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail, lang, byAdmin=false)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return optional with account
                    AccountManager -> AccountEntity: getEmail()
                    return current account email
                    AccountManager -> AccountFacadeReadCommitted: findByEmail(newEmail)
                    return empty optional
                    AccountManager -> EmailCreator: getEmailForChangeEmail(lang, newEmail, byAdmin, login, newEmail, LocalDateTime.now().toString())
                    return emailMessage
                    AccountManager -> EmailSender: sendEmail(emailMessage)
                    return success
                end
            return success
        return status code 200
    return 'link sent' message
    "Admin~/Employee~/Customer" -> ConfirmationView: link visited
            ConfirmationView -> AccountEndpoint: changeOwnEmail(toVerify)
                AccountEndpoint -> AccountManager: changeEmail(cipherText)
                    group RW, read commited
                        AccountManager -> ExpiredTokenFacadeReadCommitted: findByToken(cipherText)
                        return empty optional
                        AccountManager -> Crypt: decrypt(cipherText)
                        return decrypted login and email
                        AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                        return empty optional
                    end
                return account deleted before visiting link
            return status code 400
        return 'error' message
else email is already in use
autonumber
    "Admin~/Employee~/Customer" -> ChangeOwnEmailForm: 'submit' button clicked and confirmed
        ChangeOwnEmailForm -> AccountEndpoint: sendEmailChangeLink(newEmail, lang, captchaToken)
            AccountEndpoint -> CaptchaUtils: validateToken(captchaToken)
            return positive validation result
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> AccountManager: sendEmailForChangeEmail(principal.getName(), newEmail, lang, byAdmin=false)
                group RO, read committed
                    AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                    return optional with account
                    AccountManager -> AccountEntity: getEmail()
                    return current account email
                    AccountManager -> AccountFacadeReadCommitted: findByEmail(newEmail)
                    return empty optional
                    AccountManager -> EmailCreator: getEmailForChangeEmail(lang, newEmail, byAdmin, login, newEmail, LocalDateTime.now().toString())
                    return emailMessage
                    AccountManager -> EmailSender: sendEmail(emailMessage)
                    return success
                end
            return success
        return status code 200
    return 'link sent' message
    "Admin~/Employee~/Customer" -> ConfirmationView: link visited
            ConfirmationView -> AccountEndpoint: changeOwnEmail(toVerify)
                AccountEndpoint -> AccountManager: changeEmail(cipherText)
                    group RW, read commited
                        AccountManager -> ExpiredTokenFacadeReadCommitted: findByToken(cipherText)
                        return empty optional
                        AccountManager -> Crypt: decrypt(cipherText)
                        return decrypted login and email
                        AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                        return optional with account
                        AccountManager -> AccountFacadeReadCommitted: findByEmail(email)
                        return optional with account
                    end
                return email is already in use
            return status code 400
        return 'error' message
end
@enduml
