@startuml

autoactivate on
actor "Admin/Employee/Customer" as User
boundary MainMenu
participant AccountEndpoint
participant AccountDto
participant SecurityContext
participant Principal
participant AccountManager
control AccountFacadeReadCommitted

title MOK.11 Przeglądaj szczegóły swojego konta

alt correct
autonumber
    User -> MainMenu: "Account" button clicked
        MainMenu -> AccountEndpoint: getOwnAccountDetails()
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> Principal: getName()
            return login
            group RO, read committed
            AccountEndpoint -> AccountManager: getAccountDetails(login)
                AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                return optional with account
            return account
            end
            AccountEndpoint -> AccountDto: fromAccountEntity(account)
            return accountDto
        return status code 200\naccountDto
    return show account details
else account does not exist
autonumber
    User -> MainMenu: "Account" button clicked
        MainMenu -> AccountEndpoint: getOwnAccountDetails()
            AccountEndpoint -> SecurityContext: getCallerPrincipal()
            return principal
            AccountEndpoint -> Principal: getName()
            return login
            group RO, read committed
            AccountEndpoint -> AccountManager: getAccountDetails(login)
                AccountManager -> AccountFacadeReadCommitted: findByLogin(login)
                return empty optional
            return account does not exist
            end
        return status code 400\naccount does not exist
    return "Account does not exist" message
end
@enduml