@startuml
title
MOR.9 Przeglądaj szczegóły swojej rezerwacji
end title

autoactivate on
actor Customer
boundary ReservationsList
participant ReservationEndpoint
participant SecurityContext
participant ReservationManager
control ReservationFacadeReadCommitted
entity ReservationEntity
entity CustomerEntity
entity AccountEntity
alt reservation exists and belongs to user
autonumber
    Customer -> ReservationsList: "details" button clicked
        ReservationsList -> ReservationEndpoint: getOwnReservation(reservationNumber)
        ReservationEndpoint -> SecurityContext: getCallerPrincipal()
        return principal
        ReservationEndpoint -> Principal: getName()
        return login
            ReservationEndpoint -> ReservationManager: getOwnReservation(login, reservationNumber)
                group RO, read committed
                    ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                    return optional with reservation
                    ReservationManager -> ReservationEntity: getCustomer()
                    return optional with Customer
                    ReservationManager -> CustomerEntity: getAccount()
                    return account
                    ReservationManager -> AccountEntity: getLogin()
                    return account login
                end
            return reservation
            ReservationEndpoint -> OwnReservationDto: map(reservation)
            return ownReservationDto
            ReservationEndpoint -> OwnReservationDto: getVersion()
            return version
            ReservationEndpoint -> Crypt: encrypt(version)
            return encryptedVersion
            ReservationEndpoint -> OwnReservationDto: setVersion(encryptedVersion)
            return
            ReservationEndpoint -> OwnReservationDto: getId()
            return id
            ReservationEndpoint -> Crypt: encrypt(id)
            return encryptedId
            ReservationEndpoint -> OwnReservationDto: setId(encryptedId)
            return
        return status code 200\nownReservationDto
    return show reservation details
else reservation does not belong to user
autonumber
     Customer -> ReservationsList: "details" button clicked
             ReservationsList -> ReservationEndpoint: getOwnReservation(reservationNumber)
             ReservationEndpoint -> SecurityContext: getCallerPrincipal()
        return principal
        ReservationEndpoint -> Principal: getName()
        return login
                 ReservationEndpoint -> ReservationManager: getOwnReservation(login, reservationNumber)
                     group RO, read committed
                    ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                    return optional with reservation
                    ReservationManager -> ReservationEntity: getCustomer()
                    return optional with Customer
                    ReservationManager -> CustomerEntity: getAccount()
                    return account
                    ReservationManager -> AccountEntity: getLogin()
                    return account login
                end
                 return reservation does not belong to user
             return status code 400
         return 'error' message
else reservation does not exists
autonumber
     Customer -> ReservationsList: "details" button clicked
             ReservationsList -> ReservationEndpoint: getOwnReservation(reservationNumber)
             ReservationEndpoint -> SecurityContext: getCallerPrincipal()
        return principal
        ReservationEndpoint -> Principal: getName()
        return login
                 ReservationEndpoint -> ReservationManager: getOwnReservation(login, reservationNumber)
                     group RO, read committed
                         ReservationManager -> ReservationFacadeReadCommitted: findByReservationNumber(reservationNumber)
                         return empty optional
                     end
                 return reservation does not exist
             return status code 400
         return 'error' message
end
@enduml
