@startuml
title
MOR.17 Przeglądaj wszystkie tory
end title

autoactivate on
actor "Employee~/Customer"
boundary HomePage
participant AlleyEndpoint
participant AlleyManager
control alleyFacadeReadCommitted
autonumber
"Employee~/Customer" -> HomePage: button 'alleys' clicked
    HomePage -> AlleyEndpoint: getAllActiveAlleys()
        AlleyEndpoint -> AlleyManager: getAllActiveAlleys()
            group RO, read committed
            AlleyManager -> alleyFacadeReadCommitted: findByActive(true)
            return list of all alleys
            end
        return list of all alleys
    return status code 200, List<AlleyDto>
return show list of alleys
@enduml
