@startuml
title MOR.13 Przeglądaj opinie na temat modelu broni
autoactivate on
actor "Employee/Client"
boundary WeaponList
participant OpinionEndpoint
participant OpinionManager
control WeaponModelFacadeReadCommitted as WeaponModelFacade
entity WeaponModelEntity
alt Opinion for weapon model exist
autonumber
    "Employee/Client" -> WeaponList: "Details" button clicked
         WeaponList -> OpinionEndpoint: getAllOpinionsForWeaponModel(name)
                OpinionEndpoint -> OpinionManager: getAllOpinionsForWeaponModel(name)
                    group RO, read committed
                        OpinionManager -> WeaponModelFacade: findByName(name)
                        return optional with weapon model
                        OpinionManager -> WeaponModelEntity: getOpinions()
                        return list of all opinions for weapon model
                    end
                return list of all opinions for weapon model
         return status code 200
    return view with all opinion for selected weapon model

else No opinions for weapon model
autonumber
    "Employee/Client" -> WeaponList: "Details" button clicked
         WeaponList -> OpinionEndpoint: getAllOpinionsForWeaponModel(name)
                OpinionEndpoint -> OpinionManager: getAllOpinionsForWeaponModel(name)
                    group RO, read committed
                        OpinionManager -> WeaponModelFacade: findByName(name)
                        return optional with weapon model
                         OpinionManager -> WeaponModelEntity: getOpinions()
                         return empty list
                    end
                return empty list
         return status code 200\nempty list
    return "No opinions" message
else weapon model does not exist
autonumber
    "Employee/Client" -> WeaponList: "Details" button clicked
        WeaponList -> OpinionEndpoint: getAllOpinionsForWeaponModel(name)
                OpinionEndpoint -> OpinionManager: getAllOpinionsForWeaponModel(name)
                    group RO, read committed
                        OpinionManager -> WeaponModelFacade: findByName(name)
                        return empty optional
                    end
                return weapon model does not exist
         return status code 404
     return "weapon model not found" message
end
@enduml
