@startuml

title MOR.23 Przeglądaj szczegóły modelu broni
autoactivate on
actor "Employee/Customer" as User
boundary WeaponModelList
participant WeaponModelEndpoint
participant WeaponModelManager
control WeaponModelFacadeReadCommitted as WeaponModelFacade

alt weapon model with such name exists
autonumber
    User -> WeaponModelList: 'details' button clicked
        WeaponModelList -> WeaponModelEndpoint: getWeaponModel(name)
            WeaponModelEndpoint -> WeaponModelManager: getWeaponModel(name)
                group RW, read committed
                    WeaponModelManager -> WeaponModelFacade: findByName(name)
                    return optional with weaponModelEntity
                    WeaponModelManager -> WeaponModelEntity: isActive()
                    return true
                end
            return weaponModelEntity
            WeaponModelEndpoint -> EditWeaponModelDto: convertToDto(weaponModelEntity)
            return editWeaponModelDto
            WeaponModelEndpoint -> Crypt: encrypt(editWeaponModelDto.getId())
            return encryptedId
            WeaponModelEndpoint -> EditWeaponModelDto: setId(encryptedId)
            return success
            WeaponModelEndpoint -> Crypt: encrypt(editWeaponModelDto.getVersion())
            return encryptedVersion
            WeaponModelEndpoint -> EditWeaponModelDto: setVersion(encryptedVersion)
            return success
        return status code 200 \n editWeaponModelDto
    return show weapon model details

else weapon model with such name is inactive
autonumber
    User -> WeaponModelList: 'details' button clicked
        WeaponModelList -> WeaponModelEndpoint: getWeaponModel(name)
            WeaponModelEndpoint -> WeaponModelManager: getWeaponModel(name)
                group RW, read committed
                    WeaponModelManager -> WeaponModelFacade: findByName(name)
                    return optional with weaponModelEntity
                    WeaponModelManager -> WeaponModelEntity: isActive()
                    return false
                end
            return weapon model does not exist
        return status code 400
    return 'failed' message

else weapon model does not exist
autonumber
    User -> WeaponModelList: 'details' button clicked
        WeaponModelList -> WeaponModelEndpoint: getWeaponModel(name)
            WeaponModelEndpoint -> WeaponModelManager: getWeaponModel(name)
                group RW, read committed
                    WeaponModelManager -> WeaponModelFacade: findByName(name)
                    return empty optional
                end
            return weapon model does not exist
        return status code 400
    return 'failed' message

end
@enduml