@startuml

autoactivate on
actor Employee
boundary MainMenu
participant WeaponEndpoint
participant WeaponManager
control WeaponFacadeReadCommitted

title MOR.26 Przeglądaj wszystkie egzemplarze broni

alt any weapon exists
autonumber
    Employee -> MainMenu: 'all weapons' button clicked
        MainMenu -> WeaponEndpoint: getAllActiveWeapons()
        WeaponEndpoint -> WeaponManager: getAllActiveWeapons()
            group RO, read committed
                WeaponManager -> WeaponFacadeReadCommitted: findByActive(true)
                return all active weapons
            end
            return all active weapons
        return status code 200
    return show all active weapons
end

@enduml