@startuml

title MOR.24 Dodaj nowy egzemplarz broni
autoactivate on
actor Employee

boundary WeaponList
boundary CreateWeaponView
participant WeaponEndpoint
participant WeaponModelEndpoint
participant WeaponModelManager
participant WeaponManager
control WeaponFacadeSerializable
control WeaponModelFacadeReadCommitted
control WeaponModelFacadeSerializable
entity WeaponEntity

alt provided data is valid
autonumber
    Employee -> WeaponList: button 'add new weapon' clicked
        WeaponList -> WeaponModelEndpoint: getAllActiveWeaponModels()
            WeaponModelEndpoint -> WeaponModelManager: getAllActiveWeaponModels()
                group RO, read committed
                WeaponModelManager -> WeaponModelFacadeReadCommitted : findByActive(true)
                return list of weapon models
                end
            return list of weapon models
        return status code 200\nall weapon models
    return show add weapon form
    Employee -> CreateWeaponView: button 'add' clicked
        CreateWeaponView -> WeaponEndpoint: createWeapon(weaponDto)
            WeaponEndpoint -> WeaponEntity: <<create>>
            return weaponEntity
            WeaponEndpoint -> WeaponManager: createWeapon(weaponEntity, weaponDto.getWeaponModelName())
                group RW, serializable
                WeaponManager -> WeaponFacadeSerializable: findBySerialNumber(weaponEntity.getSerialNumber())
                return empty optional
                WeaponManager -> WeaponModelFacadeSerializable : findByName(weaponModelName)
                return optional with weapon model
                WeaponManager -> WeaponEntity : setWeaponModel(weaponModelEntity)
                return success
                WeaponManager -> WeaponFacadeSerializable: create(weaponEntity)
                return success
                end
            return success
        return status code 200
    return success confirmation
else weapon with such serial number exists
autonumber
    Employee -> WeaponList: button 'add new weapon' clicked
        WeaponList -> WeaponModelEndpoint: getAllActiveWeaponModels()
            WeaponModelEndpoint -> WeaponModelManager: getAllActiveWeaponModels()
                group RO, read committed
                WeaponModelManager -> WeaponModelFacadeReadCommitted : findByActive(true)
                return list of weapon models
                end
            return list of weapon models
        return status code 200\nall weapon models
    return show add weapon form
    Employee -> CreateWeaponView: button 'add' clicked
        CreateWeaponView -> WeaponEndpoint: createWeapon(WeaponDto)
            WeaponEndpoint -> WeaponEntity: <<create>>
            return weaponEntity
            WeaponEndpoint -> WeaponManager: createWeapon(weaponEntity, weaponDto.getWeaponModelName())
                group RW, serializable
                WeaponManager -> WeaponFacadeSerializable: findBySerialNumber(weaponEntity.getSerialNumber())
                return optional with weapon
                end
            return weapon exists
        return status code 400\nweapon exists
    return 'weapon with such serial number exists' message
else no weapon models
autonumber
    Employee -> WeaponList: button 'add new weapon' clicked
        WeaponList -> WeaponModelEndpoint: getAllActiveWeaponModels()
            WeaponModelEndpoint -> WeaponModelManager: getAllActiveWeaponModels()
                group RO, read committed
                WeaponModelManager -> WeaponModelFacadeReadCommitted : findByActive(true)
                return empty list
                end
            return empty list
        return status code 400\nempty list
    return 'no weapons models' message
else invalid form
autonumber
    Employee -> WeaponList: button 'add new weapon' clicked
        WeaponList -> WeaponModelEndpoint: getAllActiveWeaponModels()
            WeaponModelEndpoint -> WeaponModelManager: getAllActiveWeaponModels()
                group RO, read committed
                WeaponModelManager -> WeaponModelFacadeReadCommitted : findByActive(true)
                return list of weapon models
                end
            return list of weapon models
        return status code 200\nall weapon models
    return show add weapon form
    Employee -> CreateWeaponView: button 'add' clicked
        CreateWeaponView -> WeaponEndpoint: createWeapon(WeaponDto)
        return status code 400\n invalid form
    return 'invalid form' message
end

@enduml