@startuml
title
MOR.22 Przeglądaj wszystkie modele broni
end title

autoactivate on
actor "Employee~/Customer"
boundary HomePage
participant WeaponModelEndpoint
participant WeaponModelManager
control WeaponModelFacadeReadCommitted
autonumber
"Employee~/Customer" -> HomePage: button 'weapon models' clicked
    HomePage -> WeaponModelEndpoint: getAllActiveWeaponModels()
            WeaponModelEndpoint -> WeaponModelManager: getAllActiveWeaponModels()
                group RO, read committed
                WeaponModelManager -> WeaponModelFacadeReadCommitted: findByActive(true)
                return list of all WeaponModel
                end
            return list of all WeaponModel
    return status code 200, List<WeaponModelDto>
return show list of weapon models
@enduml